export const affiliateList = [
    { id: 'AFF001', name: 'Abdullahi Musa', madrasatName: 'Madrasat Nurul Huda', address: 'No. 12 Zaria Road, Kano' },
    { id: 'AFF002', name: 'Yusuf Ibrahim', madrasatName: 'Darul Hikmah Academy', address: 'Plot 4 Wuse Zone 5, Abuja' },
    { id: 'AFF003', name: 'Suleiman Abdulkadir', madrasatName: 'Madrasat Al-Furqan', address: '13 Sokoto Crescent, Kaduna' },
    { id: 'AFF004', name: 'Nasiru Mohammed', madrasatName: 'Ibrahim Islamic Center', address: '7 BUK Road, Kano' },
    { id: 'AFF005', name: 'Muktar Usman', madrasatName: 'Madrasat As-Salaam', address: '24 Emir Drive, Bauchi' },
    { id: 'AFF006', name: 'Ahmad Bello', madrasatName: 'Nurul Bayan School', address: 'No. 5 Bida Road, Minna' },
    { id: 'AFF007', name: 'Hassan Sani', madrasatName: 'Al-Hikmah Islamic School', address: '9 Tafawa Street, Gombe' },
    { id: 'AFF008', name: 'Umar Rabiu', madrasatName: 'Madrasat An-Nur', address: '33 Unity Avenue, Jos' },
    { id: 'AFF009', name: 'Kabiru Adamu', madrasatName: 'Madrasat Darul Uloom', address: '11 Zango Street, Ilorin' },
    { id: 'AFF010', name: 'Abubakar Aliyu', madrasatName: 'Al-Mustaqeem School', address: '8 Emir Road, Katsina' },
    { id: 'AFF011', name: 'Ismail Ahmed', madrasatName: 'Madrasat As-Siddiq', address: '10 GRA Layout, Sokoto' },
    { id: 'AFF012', name: 'Faruk Lawal', madrasatName: 'Darul Quran Institute', address: '21 Main Street, Lafia' },
    { id: 'AFF013', name: 'Tijjani Ibrahim', madrasatName: 'Al-Madina School', address: 'Block B, Jalingo Road, Yola' },
    { id: 'AFF014', name: 'Aliyu Garba', madrasatName: 'Madrasat Al-Ikhlas', address: '14 Bwari Close, Abuja' },
    { id: 'AFF015', name: 'Bashir Idris', madrasatName: 'Darul Arqam Center', address: '22 Railway Road, Gusau' },
    { id: 'AFF016', name: 'Sani Tijjani', madrasatName: 'Madrasat Rahmaniyya', address: '16 Limawa Road, Dutse' },
    { id: 'AFF017', name: 'Aminu Abdul', madrasatName: 'Ibn Taymiyyah Institute', address: '10 Malali Crescent, Kaduna' },
    { id: 'AFF018', name: 'Ibrahim Salisu', madrasatName: 'Madrasat As-Siraj', address: '23 Zuba Street, Abuja' },
    { id: 'AFF019', name: 'Saheed Abubakar', madrasatName: 'Al-Qalam School', address: 'Block 7, GRA Road, Ilorin' },
    { id: 'AFF020', name: 'Nura Sulaiman', madrasatName: 'Madrasat Al-Bayan', address: '17 Ring Road, Kano' },
    { id: 'AFF021', name: 'Abdulrahman Kabir', madrasatName: 'Al-Hidayah School', address: '18 Maiha Street, Yola' },
    { id: 'AFF022', name: 'Abdullahi Idris', madrasatName: 'Nurul Huda Institute', address: '45 Maiduguri Road, Damaturu' },
    { id: 'AFF023', name: 'Mansur Abdullahi', madrasatName: 'Darul Huda Academy', address: '13 Lokoja Close, Kogi' },
    { id: 'AFF024', name: 'Muhammad Aminu', madrasatName: 'Madrasat Al-Haqq', address: '19 Bagauda Road, Kano' },
    { id: 'AFF025', name: 'Hamza Yusuf', madrasatName: 'Al-Falah Islamic School', address: '22 Tudun Wada Lane, Zaria' },
    { id: 'AFF026', name: 'Ali Jibril', madrasatName: 'Madrasat Ar-Rahma', address: '31 Sabo Road, Kaduna' },
    { id: 'AFF027', name: 'Salisu Umar', madrasatName: 'Ibn Sina Academy', address: 'Block 5, Argungu Way, Birnin Kebbi' },
    { id: 'AFF028', name: 'Abdulkareem Musa', madrasatName: 'Al-Badr Islamic Institute', address: '34 Tudun Wada Street, Kano' },
    { id: 'AFF029', name: 'Faisal Abubakar', madrasatName: 'Madrasat Ar-Rayyan', address: '18 Bida Street, Minna' },
    { id: 'AFF030', name: 'Mohammed Bashir', madrasatName: 'Darul Hikmah School', address: '47 Tafawa Balewa Road, Bauchi' },
    { id: 'AFF031', name: 'Sani Bala', madrasatName: 'An-Nur Islamic School', address: '14 Zaki Biam Street, Makurdi' },
    { id: 'AFF032', name: 'Haruna Isa', madrasatName: 'Madrasat Al-Firdaws', address: '11 Kafin Hausa Street, Jigawa' },
    { id: 'AFF033', name: 'Ilyasu Ahmed', madrasatName: 'Al-Azhar Institute', address: '27 Barau Dikko Crescent, Kaduna' },
    { id: 'AFF034', name: 'Mahmud Sule', madrasatName: 'Ibn Abbas School', address: '26 Kano Road, Lokoja' },
    { id: 'AFF035', name: 'Shuaibu Musa', madrasatName: 'Madrasat Al-Muhajiroon', address: '40 Azare Street, Bauchi' },
    { id: 'AFF036', name: 'Abubakar Sadiq', madrasatName: 'Darul Iman Academy', address: '15 Rigasa Road, Kaduna' },
    { id: 'AFF037', name: 'Mustapha Umar', madrasatName: 'Al-Bayyinah School', address: 'Block 11, Jos North, Jos' },
    { id: 'AFF038', name: 'Rabiu Hassan', madrasatName: 'Madrasat Al-Ma’arif', address: '17 GRA Extension, Damaturu' },
    { id: 'AFF039', name: 'Khalid Lawal', madrasatName: 'Ibn Kathir School', address: '42 Market Road, Gombe' },
    { id: 'AFF040', name: 'Abdulazeez Sulaiman', madrasatName: 'As-Sirat Institute', address: '6 Argungu Road, Sokoto' },
    { id: 'AFF041', name: 'Jamilu Tukur', madrasatName: 'Madrasat Al-Amin', address: '19 Angwan Rimi, Zaria' },
    { id: 'AFF042', name: 'Mohammed Adamu', madrasatName: 'Madrasat Darul Ihsan', address: '23 Gashua Street, Yobe' },
    { id: 'AFF043', name: 'Sagir Bello', madrasatName: 'Ibn Uthaymeen School', address: '29 Azare Crescent, Bauchi' },
    { id: 'AFF044', name: 'Abdulmalik Ibrahim', madrasatName: 'Madrasat Ar-Rasheed', address: '18 Gusau Road, Zamfara' },
    { id: 'AFF045', name: 'Mikail Abdullahi', madrasatName: 'Al-Istiqamah School', address: '5 Mubi Road, Adamawa' },
    { id: 'AFF046', name: 'Kabir Musa', madrasatName: 'Darul Fikr School', address: '33 Katsina Road, Daura' },
    { id: 'AFF047', name: 'Usman Aliyu', madrasatName: 'An-Nasr Institute', address: '41 Jalingo Street, Taraba' },
    { id: 'AFF048', name: 'Sule Usman', madrasatName: 'Al-Burhan Islamic School', address: '15 GRA Phase 2, Ilorin' },
    { id: 'AFF049', name: 'Ahmad Rabiu', madrasatName: 'Madrasat Al-Majd', address: '36 Gombe Road, Bauchi' },
    { id: 'AFF050', name: 'Isah Aminu', madrasatName: 'Al-Haqq Academy', address: '8 Jos Street, Makurdi' },
    { id: 'AFF051', name: 'Nuhu Garba', madrasatName: 'Madrasat Al-Miftah', address: '22 Sabon Gari, Kano' },
    { id: 'AFF052', name: 'Zubair Musa', madrasatName: 'Ibn Hajar School', address: '20 Emir Street, Katsina' },
    { id: 'AFF053', name: 'Hassan Ibrahim', madrasatName: 'Madrasat As-Sajid', address: '7 Zuru Street, Kebbi' },
    { id: 'AFF054', name: 'Bello Abdullahi', madrasatName: 'Al-Bayan Islamic School', address: '15 Lafia Road, Nassarawa' },
    { id: 'AFF055', name: 'Muhsin Sadiq', madrasatName: 'Ibn Taymiyyah School', address: '5 Sabon Tasha Street, Kaduna' },
    { id: 'AFF056', name: 'Abdulkadir Umar', madrasatName: 'Nurul Bayan School', address: '6 Tudun Wada Lane, Abuja' },
    { id: 'AFF057', name: 'Ibrahim Jibril', madrasatName: 'Darul Hikmah Academy', address: '12 Mubi Street, Adamawa' },
    { id: 'AFF058', name: 'Suleiman Nasir', madrasatName: 'Madrasat As-Sakinah', address: '19 GRA Phase 1, Minna' },
    { id: 'AFF059', name: 'Yahaya Sule', madrasatName: 'Al-Mubarak School', address: '4 Jimeta Street, Yola' },
    { id: 'AFF060', name: 'Auwalu Idris', madrasatName: 'Madrasat Ar-Rahmah', address: '10 Tudun Maliki Road, Kano' },
    { id: 'AFF061', name: 'Muktar Aliyu', madrasatName: 'Darul Khair School', address: '7 Tunga Street, Minna' },
    { id: 'AFF062', name: 'Abdulaziz Musa', madrasatName: 'Madrasat As-Sadiqeen', address: '18 Gusau Road, Zamfara' },
    { id: 'AFF063', name: 'Sagir Usman', madrasatName: 'Al-Huda School', address: '22 Dala Hill Road, Kano' },
    { id: 'AFF064', name: 'Ismail Tukur', madrasatName: 'Ibn Qayyim School', address: '31 Potiskum Road, Yobe' },
    { id: 'AFF065', name: 'Jibrin Yusuf', madrasatName: 'Darul Firdaws School', address: '9 Airport Road, Kano' },
    { id: 'AFF066', name: 'Aminu Hassan', madrasatName: 'Al-Mutakabbir School', address: '15 New Market Road, Gombe' },
    { id: 'AFF067', name: 'Hassan Lawan', madrasatName: 'Al-Furqan Academy', address: '16 Numan Road, Adamawa' },
    { id: 'AFF068', name: 'Kabir Abdulrahman', madrasatName: 'Madrasat Al-Mubarak', address: '23 Tudun Wada, Kaduna' },
    { id: 'AFF069', name: 'Mustapha Garba', madrasatName: 'Nurul Iman School', address: '18 Jos South, Jos' },
    { id: 'AFF070', name: 'Abdullahi Saidu', madrasatName: 'Madrasat Darul Islam', address: '26 Lafia Road, Nasarawa' },
    { id: 'AFF071', name: 'Muhammad Sani', madrasatName: 'Madrasat Al-Bashir', address: '14 Yelwa Road, Bauchi' },
    { id: 'AFF072', name: 'Ismaila Usman', madrasatName: 'Darul Khairaat', address: '5 Argungu Road, Sokoto' },
    { id: 'AFF073', name: 'Nura Lawan', madrasatName: 'Madrasat Al-Mu’minun', address: '11 Mariri Road, Kano' },
    { id: 'AFF074', name: 'Tijjani Haruna', madrasatName: 'Al-Mufeed Islamic School', address: '33 Wurno Road, Gusau' },
    { id: 'AFF075', name: 'Yunusa Musa', madrasatName: 'Madrasat As-Safa', address: '18 Karu Road, Abuja' },
    { id: 'AFF076', name: 'Umar Yakubu', madrasatName: 'Al-Ihsan School', address: '10 Talata Road, Zamfara' },
    { id: 'AFF077', name: 'Sule Gambo', madrasatName: 'Madrasat As-Siratul Mustaqeem', address: '22 Benue Street, Makurdi' },
    { id: 'AFF078', name: 'Ahmad Abdullahi', madrasatName: 'Ibn Jawzi School', address: '19 Ikotun Road, Abuja' },
    { id: 'AFF079', name: 'Nasiru Salisu', madrasatName: 'Madrasat Al-Qudwah', address: '16 Zaria Road, Kaduna' },
    { id: 'AFF080', name: 'Muhsin Abdullahi', madrasatName: 'Al-Qalam Institute', address: '21 Malumfashi Street, Katsina' },
    { id: 'AFF081', name: 'Abubakar Tukur', madrasatName: 'Madrasat Nurul Bayan', address: '28 Tunga Road, Minna' },
    { id: 'AFF082', name: 'Ishaq Umar', madrasatName: 'Darul Maarifah', address: '12 Ningi Street, Bauchi' },
    { id: 'AFF083', name: 'Usman Shehu', madrasatName: 'Madrasat Al-Hikmah', address: '30 Sardauna Crescent, Kano' },
    { id: 'AFF084', name: 'Ibrahim Khalid', madrasatName: 'Madrasat An-Nur', address: '27 Suleja Street, Abuja' },
    { id: 'AFF085', name: 'Abdulkadir Musa', madrasatName: 'Al-Ma’arif Institute', address: '17 Mando Road, Kaduna' },
    { id: 'AFF086', name: 'Yahaya Idris', madrasatName: 'Darul Salam School', address: '19 Okene Road, Kogi' },
    { id: 'AFF087', name: 'Tukur Adamu', madrasatName: 'Madrasat An-Naim', address: '4 Jega Street, Kebbi' },
    { id: 'AFF088', name: 'Lukman Yusuf', madrasatName: 'Nurul Huda Islamic Center', address: '21 Bauchi Road, Jos' },
    { id: 'AFF089', name: 'Ibrahim Bala', madrasatName: 'Madrasat Al-Badr', address: '11 Gboko Street, Benue' },
    { id: 'AFF090', name: 'Usman Abdulkareem', madrasatName: 'Al-Mahdi School', address: '13 Samaru Road, Zaria' },
    { id: 'AFF091', name: 'Nasir Ibrahim', madrasatName: 'Madrasat Al-Mujtaba', address: '32 Akwanga Street, Nasarawa' },
    { id: 'AFF092', name: 'Hamisu Bashir', madrasatName: 'Al-Wali School', address: '27 Ajingi Road, Kano' },
    { id: 'AFF093', name: 'Abdullahi Yahaya', madrasatName: 'Madrasat Al-Wahda', address: '29 GRA Street, Lokoja' },
    { id: 'AFF094', name: 'Tanimu Sulaiman', madrasatName: 'Darul Ma’arifa School', address: '14 Ilesha Street, Abuja' },
    { id: 'AFF095', name: 'Gambo Lawal', madrasatName: 'Madrasat Al-Muhaajir', address: '20 Jalingo Road, Taraba' },
    { id: 'AFF096', name: 'Mansur Suleiman', madrasatName: 'Madrasat An-Nusrah', address: '7 Dambatta Street, Kano' },
    { id: 'AFF097', name: 'Umaru Bello', madrasatName: 'Madrasat Al-Mushaf', address: '12 Tudun Maliki Crescent, Kano' },
    { id: 'AFF098', name: 'Idris Isa', madrasatName: 'Darul Taqwa School', address: '26 Kurfi Street, Katsina' },
    { id: 'AFF099', name: 'Abdulwahid Musa', madrasatName: 'Madrasat Ar-Rashideen', address: '30 Gusau Crescent, Sokoto' },
    { id: 'AFF100', name: 'Ibrahim Garba', madrasatName: 'Ibn Mas’ud Islamic School', address: '15 Lafia Crescent, Nasarawa' }
  ];
  
 
  